#pragma once

#include <utility>

enum testList {
	SIMPL_TEST = 0,
	NEG_SIZE_TEST,
	NEGROW_TEST,
	UNBOUNDED_TEST,
	INFEASIBLE_TEST,
	EXPORT_TEST,
	IMPORT_TEST,
	NEGATIVE_IMPORT_TEST,

	NUMBER_OF_TESTS
};

enum testErrorCodes {
	TEST_SUCCESS,
	TEST_INCORRECT_VALUE,
	TEST_UNEXPECTED_VALUE,
	TEST_INCORRECT_OPTIMAL_VALUE,
	TEST_INCORRECT_OPERATION,
	TEST_BLOCKED_CORRECT_OPERATION,
	TEST_SIMPLEX_ERROR,
	TEST_NOT_IMPLEMENTED_FUNCTION


};

#define testResultCodes std::pair<testList, testErrorCodes>